---
title: "ROC_LiftChart_1"
output: pdf_document
---

```{r include=FALSE}
#install.packages('party')
#install.packages('ROCR')
#install.packages('rpart')
require(party)
require(ROCR)
require(rpart)
```

### Question 1
```{r include=TRUE}
# Load the kyphosis data set.
df <- rpart::kyphosis
summary(df)
```

```{r}
# Split randomly onto 70% training and 30% testing set
# Write your code below
set.seed(123)
divide <- sample(2,nrow(df),replace = TRUE, prob = c(0.7,0.3))
x_train <- df[divide == 1,]
x_test <- df[divide == 2,]
```

```{r}
# load the libraries
#install.packages("caret")
#install.packages("e1071")
library(caret)
library(e1071)
# Do Not change the following code
model <- cforest(Kyphosis ~ ., data=x_train, control = cforest_unbiased(mtry = 3))
model
prediction_val <- predict(model, newdata=x_test)
prediction_val
# summarize results
confusionMatrix(prediction_val, x_test$Kyphosis)
```


```{r}
# Use the above model and the validation set to create a ROC curve and Lift Chrat(Gaine chart)
# Write your code below
# ROC Curve
prob <- 1- unlist(treeresponse(model,newdata = x_test), use.names=F)[seq(1,nrow(x_test)*2,2)]
pred <- prediction(prob, x_test$Kyphosis)
roc <- performance(pred,"tpr","fpr")
plot(roc, main="ROC curve", colorize=T)
```

```{r}
# Lift Curve
lift <- performance(pred,"tpr","rpp")
plot(lift, main="Lift curve", colorize=T)
```



